Repository Devcourse-BE6-8-2-Team04/Frontend, pull requests merged in 2025-08, with the labels that each got.

#42 feature: Comment 목록 및 상세페이지 반응형으로 구현
  src/app/comments/[id]/page.tsx
  src/app/comments/page.tsx
  src/app/globals.css
  src/components/layout/NavBar.tsx
  src/features/comment/components/ActiveFilters.tsx
  src/features/comment/components/CommentCard.tsx
  src/features/comment/components/CommentHeader.tsx
  src/features/comment/components/CommentInfo.tsx
  src/features/comment/components/CommentItem.tsx
  src/features/comment/components/CommentsHeader.tsx
  src/features/comment/components/CommentsList.tsx
  src/features/comment/components/CommentsMain.tsx
  src/features/comment/components/LoadingSpinner.tsx
  src/features/comment/components/Pagination.tsx
  src/features/comment/components/ResultsCount.tsx
  src/features/comment/components/SearchFilters.tsx
  src/features/comment/components/WeatherInfo.tsx
  src/features/comment/hooks/useComment.ts
  src/features/comment/modals/ConfirmModal.tsx
  src/features/comment/modals/Modal.tsx
  src/features/comment/modals/PasswordModal.tsx
  src/features/comment/types/index.ts
Labels: feature

#44 Perf : 공통 모듈 적용 및 보기 방법 추가
  src/app/plan/components/ClothResults.tsx
  src/app/plan/components/PlanForm.tsx
  src/app/plan/components/ResultsDisplay.tsx
  src/app/plan/components/WeatherResults.tsx
  src/app/plan/hooks/usePlan.ts
  src/app/plan/page.tsx
  src/app/plan/types.ts
Labels: perf

#43 feature: 메인 화면 날씨별 배경 이미지 변경 기능
  public/images/bg-atmosphere-dust.png
  public/images/bg-atmosphere-fog.png
  public/images/bg-atmosphere-squalls.png
  public/images/bg-atmosphere-tornado.png
  public/images/bg-atmosphere-volcanic.png
  public/images/bg-clear.png
  public/images/bg-cloud-overcast.png
  public/images/bg-cloud.png
  public/images/bg-rain-freezing.png
  public/images/bg-rain-heavy.png
  public/images/bg-rain-light.png
  public/images/bg-rain-shower.png
  public/images/bg-snow-heavy.png
  public/images/bg-snow-light.png
  public/images/bg-snow-sleet.png
  public/images/bg-snow.png
  public/images/bg-thunderstorm-heavy.png
  public/images/bg-thunderstorm-light.png
  public/images/bg-thunderstorm-ragged.png
  public/images/bg-thunderstorm.png
  public/images/char-normal-clear.png
  src/features/weather/components/WeatherTodayCard.tsx
  src/features/weather/components/WeeklyForecastSwiper.tsx
  src/features/weather/utils/weatherBackgroundMap.ts
  src/features/weather/utils/weatherCharacterMap.ts
  src/features/weather/utils/weatherThemeMap.ts
Labels: feature

#50 feature: Comment 목록 UI 개선
  src/components/layout/NavBar.tsx
  src/features/comment/components/ActiveFilters.tsx
  src/features/comment/components/CommentHeader.tsx
  src/features/comment/components/CommentItem.tsx
  src/features/comment/components/CommentsHeader.tsx
  src/features/comment/components/CommentsMain.tsx
  src/features/comment/components/SearchFilters.tsx
  src/features/comment/types/index.ts
Labels: feature

#52 perf: Comment 관련 페이지에 날씨 아이콘 추가, plan 페이지와 comment 페이지 연결
  src/app/plan/components/CommentsLink.tsx
  src/app/plan/components/ResultsDisplay.tsx
  src/features/comment/components/CommentCard.tsx
  src/features/comment/components/CommentItem.tsx
  src/features/comment/components/CommentsMain.tsx
  src/features/comment/components/SearchFilters.tsx
  src/features/comment/components/WeatherInfo.tsx
Labels: perf

#56 fix: plan 페이지 이미지 로드 오류 해결
  next.config.ts
Labels: fix
